export const CONST = {
  INFO_INDEX: 0,
  DEFAULT_TIMEOUT: 0,
  ATTRIBUTE_REQUIRED: 'required', // need to match error type returned by validator
  ATTRIBUTE_NUMONLY: 'numOnly',
  ATTRIBUTE_MIN_LENGTH: 'minlength',
  ATTRIBUTE_MAX_LENGTH: 'maxlength',
  ATTRIBUTE_DOLLAR: 'dollar',
  ATTRIBUTE_DATE: 'date',
  ATTRIBUTE_DATE_OF_Birth: 'dob',
  ATTRIBUTE_NO_SPECIAL_CHAR: 'NoSpecialChar',
  ATTRIBUTE_TRIM: 'Trim',
  ATTRIBUTE_ZIPCODE: 'ZipCode',
  ATTR_MANDATORY: 'Mandatory',
  ATTR_NUM_ONLY: 'Number Only',
  ATTR_LENGTH_MIN: 'Min Length',
  ATTR_LENGTH_MAX: 'Max Length',
  BR_A_CODE_04: 'Dollar',
  BR_A_CODE_05: 'Date',
  BR_A_CODE_06: 'NoSpecialChar',
  BR_A_CODE_07: 'NoSpecialChar',
  BR_A_CODE_08: 'Trim',
  BR_A_CODE_09: 'ZipCode',
  CONNECTION_SHOW: 'show',
  CONNECTION_HIDE: 'hide',
  CONNECTION_ENABLE: 'enable',
  CONNECTION_DISABLE: 'disable',
  EDIT_INDEX: 0,
  TEXT_INPUT_URL: 'assets/text-input.config.json',
  RADIO_INPUT_URL: 'assets/radio-input.multi.config.json',
  FORMATED_INPUT_URL: 'assets/formated-input.config.json',
  SELECT_INPUT_URL: 'assets/select-input.config.json',
  TEXT_INPUT: 'Text Input',
  RADIO_INPUT: 'Radio Input',
  SELECT_INPUT: 'Select Input',
  FORMATED_INPUT: 'Formated Input',
  WORKSHOP: 'workshop',
  WORKSHOP_TOOLSETS_URL: 'assets/workshop/workshop-toolsets.json',
  WORKSHOP_TOOLSETS2_URL: 'assets/workshop/workshop-dynamic.json',
  WHITEBOARD: 'White Board',
  ENABLEEDITING: true,
  REQUIRED: ' required',
  ERROR_MSG_ONLY_NUMB_ALLOWED: 'Only Number is Allowed',
  ERROR_MSG_MIN_LENGTH: 'Min Characters Required',
  ERROR_MSG_MAX_LENGTH: 'Max Characters Required',
  REAL_TIME: 'realTime',
  ON_BLUR: 'onBlur',
  ON_CLICK: 'onClick',
  TEMP_PLACEHOLDER: 'temp_placeholder',
  LEFT_PANEL_ID: 'ui-lib',
  RIGHT_PANEL_ID: 'operation-console',
  APP_ID: 'mgfb-id',
  APPP_SECRET_PUBLIC: '',
};
